
const importAll = r => {
    let images = {};
    r.keys().map((item, index) => { return images[item.replace('./', '')] = r(item); });
    return images;
}
const images = importAll(require.context('./assets/foodImages', false, /\.(png|jpg|svg)$/));

const data = {
    productData: [
        {
            id: 1,
            img: images['green chili.jpg'],
            title: 'Green Chili-250g',
            desc: "Green chile peppers widely vary in size and shape, appearing slightly curved to straight, and can contain different levels of spice depending on the individual variety.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 2,
            img: images['cucumber.jpg'],
            title: 'Hybrid Cucumber-500g',
            desc: "Cucumber is a summer vegetable, with elongate shape and 15cm long. Its skin is of a green colour, turning into yellow in maturation.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 3,
            img: images['onion.jpg'],
            title: 'Onion-1kg',
            desc: 'Onions are cultivated and used around the world. As a food item, they are usually served cooked, as a vegetable or part of a prepared savoury dish, but can also be eaten raw ',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 4,
            img: images['okra.jpg'],
            title: 'Okra-500g',
            desc: "Okra grows in an elongated, lantern shape vegetable. It is a fuzzy, green colored, and ribbed pod that is approximately 2-7 inches in length.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 5,
            img: images['lemon.jpg'],
            title: 'Lemon-4pcs',
            desc: "The lemon is a round, slightly elongated fruit, it has a strong and resistant skin, with an intense bright yellow colour when it is totaly ripe, giving off a special aroma when it is cut",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 6,
            img: images['mint.jpg'],
            title: 'Mint Leaves-100g',
            desc: "Mint Leaves are produced from good quality, cleaned dried leaves of Mentha viridas and are dark green in colour with a strong clean sweet menthol flavour profile",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 7,
            img: images['sweet potato.jpg'],
            title: 'Sweet Potato-1kg',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 8,
            img: images['pumpkin.jpg'],
            title: 'Pumpkin-1slice',
            desc: "A pumpkin is a cultivar of winter squash that is round with smooth, slightly ribbed skin, and is most often deep yellow to orange in coloration. ",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 9,
            img: images['potato.jpg'],
            title: 'Potato-1kg',
            desc: "The potato is a tuber, round or oval, with small white roots called eyes, that are growth buds. The size varies depending on the variety; the colour of the skin can be white, yellow or even purple. ",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 10,
            img: images['papaya.jpg'],
            title: 'Green Papaya-1kg',
            desc: "The Green papaya fruit weighs an average of one to two pounds. It is pear-shaped with a true green peel and a pale translucent yellow-green flesh that bears a pocket of seeds in its central core. The flesh and the seeds are the edible part of the fruit.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 11,
            img: images['eggplant.jpg'],
            title: 'Eggplant',
            desc: "The stem is often spiny. The flowers are white to purple in color, with a five-lobed corolla and yellow stamens.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 12,
            img: images['banana.jpg'],
            title: 'Green Banana-4pcs',
            desc: "Green bananas are raw bananas, which are quite firm in texture. They are at their immature stage where they have not yet ripened.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 13,
            img: images['carrot.jpg'],
            title: 'Carrot-500g',
            desc: "Carrot is a biennial, belonging to the family Apiaceae, and is an important vegetable for its fleshy edible, colorful roots. It varies in colour from white, yellow, orange, light purple, deep red to deep violet.",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 14,
            img: images['red chilli.jpg'],
            title: 'Red Chilli-200g',
            desc: "Dried red chilli powder is a major food ingredient in Indian and international cuisines. Red chilli powder brings its characteristic bright red color and pungency to any preparation it is used in",
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 15,
            img: images['coco powder.jpg'],
            title: 'Coco Powder-500gm',
            desc: "Coco powder is the fine ground brown powder obtained from the partially or completely defatted portion of cocoa liquor or mass of fermented cocoa beans",
            category: 'Baking Needs',
            price: 300,
        },
        {
            id: 16,
            img: images['baking.jpg'],
            title: 'Baking Powder-250gm',
            desc: "Baking soda, also known as bicarbonate of soda or sodium bicarbonate, is a chemical leavening agent commonly used in baked goods. Baking soda is a base alkaline compound, which means it is not acidic",
            category: 'Baking Needs',
            price: 110,
        },
        {
            id: 17,
            img: images['salt.jpg'],
            title: 'Salt -1kg',
            desc: "Salt is an important natural preservative and has been used for centuries to preserve meat, fish, dairy products and many other foods.",
            category: 'Daily cooking',
            price: 35,
        },
        {
            id: 18,
            img: images['lentils.jpg'],
            title: 'Mixed Lentils-1kg',
            desc: "garlib and herbs mix is a mix of 4-5 different types of lentils. Commonly used in curries, it has a high rich protein content and is very healthy.",
            category: 'Daily cooking',
            price: 150,
        },
        {
            id: 19,
            img: images['gorom masala.jpg'],
            title: 'Gorom Masala-100gm',
            desc: "Garam masala is a spice blend widely used in Indian cuisine, from curries and lentil dishes to soups. Whole spices of cinnamon, mace, peppercorns, coriander seeds, cumin seeds, and cardamon pods are toasted in a pan to release their aromatic flavors, then ground to a powder",
            category: 'Daily cooking',
            price: 60,
        },
        {
            id: 20,
            img: images['basmati rice.jpg'],
            title: 'Basmati Rice-1kg',
            desc: 'Basmati Rice is selected from high quality rice. The health advantages of rice is its ability to produce and keep instant energy. ',
            category: 'Daily cooking',
            price: 200,
        },
        {
            id: 21,
            img: images['rice.jpg'],
            title: 'Natural Minicate Rice-5kg',
            desc: 'Natural Minicate Rice is selected from high quality rice. The health advantages of rice is its ability to produce and keep instant energy. ',
            category: 'Daily cooking',
            price: 410,
        },
        {
            id: 22,
            img: images['milk powder.jpg'],
            title: 'Milk powder-400gm',
            desc: "Goalini Fortified contains high quality protein which helps to develop overall growth . It contains vitamins and several minerals in the making . It is consisted of essential amino acids that everyone need.",
            category: 'Dairy',
            price: 350,
        },
        {
            id: 23,
            img: images['milk.jpg'],
            title: 'FarmFresh Milk- 1 Litre',
            desc: "FarmFresh Pasteurized Milk is collected from homestead dairy farmers across Bangladesh everyday, the milk is being pasteurized to make it germ free, healthy, fresh-testing and flavorful.",
            category: 'Dairy',
            price: 65,
        },
        {
            id: 24,
            img: images['yougurt.jpg'],
            title: 'Sweet Yougurt-1kg',
            desc: "Made from pasteurized toned milk and active culture, contains 3 percent fat, thick and natural taste.No added preservatives, emulsifiers, stabilizers or other artificial ingredients",
            category: 'Dairy',
            price: 90,
        },
        {
            id: 25,
            img: images['chocolate.jpg'],
            title: 'Dark chocolate-60gm',
            desc: 'Relish happy moments with your loved ones with a Cadbury Dairy Milk Chocolate block.',
            category: 'Chocolate and candy',
            price: 160,
        },
        {
            id: 26,
            img: images['candies.jpg'],
            title: '1 packet Candy-100 candies',
            desc: "Cadbury temptations brings you a delicious premium candy in rum and raisin flavour. ",
            category: 'Chocolate and candy',
            price: 150,
        },
        {
            id: 27,
            img: images['handwash.jpg'],
            title: 'Dettol Handwash- 500ml',
            desc: "Dettol Handwash protects hands from germs and gives 10 times better protection. Dettol's Trusted Germ Protection formula keeps you healthy and protected from 100 illness causing germs. Use Dettol Liquid Handwash to protect your hands from germs! Comes with a free 50ml Hand Sanitizer too!",
            category: 'Hygiene & essential',
            price: 160,
        },
        {
            id: 28,
            img: images['body wash.jpg'],
            title: 'Dettol Bodywash- 500ml',
            desc: 'Dettol bodywash Original gets us the most cost Effective germ Protection every day . Recommended By The Bangladesh Private Medical Practitioners Association (BPMPA) . It Comes with a classic fragrance and assuring safety from germs and other infection',
            category: 'Hygiene & essential',
            price: 250,
        },
        {
            id: 29,
            img: images['detol soap.jpg'],
            title: 'Dettol soap',
            desc: "Dettol Soap Original gets us the most cost Effective germ Protection every day . Recommended By The Bangladesh Private Medical Practitioners Association (BPMPA) . It Comes with a classic fragrance and assuring safety from germs and other infection",
            category: 'Hygiene & essential',
            price: 50,
        },
        {
            id: 30,
            img: images['coca cola.jpg'],
            title: 'Coca-cola - 1litre',
            desc: "Coca Cola is bold, refreshing cola perfect for parties, meals, and anywhere you need to make a big impression.Country of Origin: Bangladesh",
            category: 'Beverage',
            price: 60,
        },
        {
            id: 31,
            img: images['banana.jpg'],
            title: 'Banana-6pcs',
            desc: "The banana is a lengthy yellow fruit, found in the market in groups of three to twenty fruits, similar to a triangular cucumber, oblong and normally yellow.",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 32,
            img: images['orange.jpg'],
            title: 'Orange-1kg',
            desc: "The orange is a usually round or oval citrus; its rind and flesh are generally orange, except the varieties of red pulp.",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 33,
            img: images['guava.jpg'],
            title: 'Guava-1kg',
            desc: "The fruit has a light yellow or pink pulp, is eaten fresh or as preserves, ",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 34,
            img: images['apple.jpg'],
            title: 'Green Apple-1kg',
            desc: "Apples are high in pectin fibre. Apples boost metabolic levels, help improve heart health and regulate body's blood sugar levels by regulating the release of sugar. They are also packed with vitamin and minerals that promote healthy bones, teeth and skin",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 35,
            img: images['mango.jpg'],
            title: 'Green Manago-1kg',
            desc: "This Green mangoes aren't ripe, sweet and very yellow but more raw, tangy, sour and have more bite to them.",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 36,
            img: images['pineapple.jpg'],
            title: 'Pineapple-1pc',
            desc: "Pineapples have yellow or white pulp, fleshy, aromatic, juicy and sweet. In the fruit there is a fibrous axis that extends from the crown to the pedicle.",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 37,
            img: images['lycee.jpg'],
            title: 'Lychee-50pcs',
            desc: "Lychees are round or oblong in shape and are 1 ½ to 2 inches in diameter. Their opaque white flesh is fragrant and sweet, with floral notes",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 38,
            img: images['pomegranate.jpg'],
            title: 'Pomegranate-200g',
            desc: "Red-purple in color, the pomegranate fruit husk has two parts: an outer, hard pericarp, and an inner, spongy mesocarp",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 39,
            img: images['grapes.jpg'],
            title: 'Grapes-500g',
            desc: "a smooth-skinned juicy light green or deep red to purplish black berry eaten dried or fresh as a fruit or fermented to produce wine.",
            category: 'Fruits',
            price: 410,
        },
        {
            id: 40,
            img: images['dates.jpg'],
            title: 'Dates-500g',
            desc: "Outside the dates are wrinkled but inside they are soft, juicy and sticky. They have a delicious, deep flavor of caramel, so much so that you can not believe you are eating a fruit",
            category: 'Fruits',
            price: 410,
        },
    ]
};

export default data;


