
const importAll = r => {
    let images = {};
    r.keys().map((item, index) => { return images[item.replace('./', '')] = r(item); });
    return images;
}
const images = importAll(require.context('./assets/foodImages', false, /\.(png|jpg|svg)$/));

const data = {
    productData: [
        {
            id: 1,
            img: images['green chili.jpg'],
            title: 'Green Chili-250g',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 2,
            img: images['cucumber.jpg'],
            title: 'Hybrid Cucumber-500g',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 3,
            img: images['onion.jpg'],
            title: 'Onion-1kg',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 4,
            img: images['okra.jpg'],
            title: 'Okra-500g',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 5,
            img: images['lemon.jpg'],
            title: 'Lemon-4pcs',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 6,
            img: images['mint.jpg'],
            title: 'Mint Leaves-100g',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 7,
            img: images['sweet potato.jpg'],
            title: 'Sweet Potato-1kg',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 8,
            img: images['pumpkin.jpg'],
            title: 'Pumpkin-1slice',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 9,
            img: images['potato.jpg'],
            title: 'Potato-1kg',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 10,
            img: images['papaya.jpg'],
            title: 'Green Papaya-1kg',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 11,
            img: images['eggplant.jpg'],
            title: 'Eggplant',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 12,
            img: images['banana.jpg'],
            title: 'Green Banana-4pcs',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 13,
            img: images['carrot.jpg'],
            title: 'Carrot-500g',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 14,
            img: images['red chilli.jpg'],
            title: 'Red Chilli-200g',
            desc: '',
            category: 'Vegetables',
            price: 46,
        },
        {
            id: 15,
            img: images['coco powder.jpg'],
            title: 'Coco Powder-500gm',
            desc: '',
            category: 'Baking Needs',
            price: 300,
        },
        {
            id: 16,
            img: images['baking.jpg'],
            title: 'Baking Powder-250gm',
            desc: '',
            category: 'Baking Needs',
            price: 110,
        },
        {
            id: 17,
            img: images['salt.jpg'],
            title: 'Salt -1kg',
            desc: '',
            category: 'Daily cooking',
            price: 35,
        },
        {
            id: 18,
            img: images['lentils.jpg'],
            title: 'Mixed Lentils-1kg',
            desc: '',
            category: 'Daily cooking',
            price: 150,
        },
        {
            id: 19,
            img: images['gorom masala.jpg'],
            title: 'Gorom Masala-100gm',
            desc: '',
            category: 'Daily cooking',
            price: 60,
        },
        {
            id: 20,
            img: images['basmati rice.jpg'],
            title: 'Basmati Rice-1kg',
            desc: '',
            category: 'Daily cooking',
            price: 200,
        },
        {
            id: 21,
            img: images['rice.jpg'],
            title: 'Natural Minicate Rice-5kg',
            desc: '',
            category: 'Daily cooking',
            price: 410,
        },
        {
            id: 22,
            img: images['milk powder.jpg'],
            title: 'Milk powder-400gm',
            desc: '',
            category: 'Dairy',
            price: 350,
        },
        {
            id: 23,
            img: images['milk.jpg'],
            title: 'FarmFresh Milk- 1 Litre',
            desc: '',
            category: 'Dairy',
            price: 65,
        },
        {
            id: 24,
            img: images['yougurt.jpg'],
            title: 'Sweet Yougurt-1kg',
            desc: '',
            category: 'Dairy',
            price: 90,
        },
        {
            id: 25,
            img: images['chocolate.jpg'],
            title: 'Dark chocolate-60gm',
            desc: '',
            category: 'Chocolate and candy',
            price: 160,
        },
        {
            id: 26,
            img: images['candies.jpg'],
            title: '1 packet Candy-100 candies',
            desc: '',
            category: 'Chocolate and candy',
            price: 150,
        },
        {
            id: 27,
            img: images['handwash.jpg'],
            title: 'Dettol Handwash- 500ml',
            desc: '',
            category: 'Hygiene & essential',
            price: 160,
        },
        {
            id: 28,
            img: images['body wash.jpg'],
            title: 'Dettol Bodywash- 500ml',
            desc: '',
            category: 'Hygiene & essential',
            price: 250,
        },
        {
            id: 29,
            img: images['detol soap.jpg'],
            title: 'Dettol soap',
            desc: '',
            category: 'Hygiene & essential',
            price: 50,
        },
        {
            id: 30,
            img: images['coca cola.jpg'],
            title: 'Coca-cola - 1litre',
            desc: '',
            category: 'Beverage',
            price: 60,
        },
        {
            id: 31,
            img: images['banana.jpg'],
            title: 'Banana-6pcs',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 32,
            img: images['orange.jpg'],
            title: 'Orange-1kg',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 33,
            img: images['guava.jpg'],
            title: 'Guava-1kg',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 34,
            img: images['apple.jpg'],
            title: 'Green Apple-1kg',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 35,
            img: images['mango.jpg'],
            title: 'Green Manago-1kg',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 36,
            img: images['pineapple.jpg'],
            title: 'Pineapple-1pc',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 37,
            img: images['lycee.jpg'],
            title: 'Lychee-50pcs',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 38,
            img: images['pomegranate.jpg'],
            title: 'Pomegranate-200g',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 39,
            img: images['grapes.jpg'],
            title: 'Grapes-500g',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
        {
            id: 40,
            img: images['dates.jpg'],
            title: 'Dates-500g',
            desc: '',
            category: 'Fruits',
            price: 410,
        },
    ]
};

export default data;


